<?php

namespace Follower\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{
}
