<?php

namespace Follower\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReShareRepository extends EntityRepository
{
}
